version: '3.8'
services:
  app:
    container_name: "${APP_NAME}"
    build: ./
    ports:
      - "${DOCKER_PORT}:${HOST_PORT}"
    tty: true
    volumes:
      - ./src:/usr/src/src
    environment:
      PORT: "${HOST_PORT}"
